# Generated by Django 2.1.1 on 2018-10-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pushups', '0006_auto_20181011_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='pushups',
        ),
    ]
