# Generated by Django 2.1.1 on 2018-10-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pushups', '0008_match_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='assist',
        ),
        migrations.RemoveField(
            model_name='player',
            name='deaths',
        ),
        migrations.RemoveField(
            model_name='player',
            name='games',
        ),
        migrations.RemoveField(
            model_name='player',
            name='kills',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pushups',
        ),
    ]
